(base) [hacker@hackerbook Secure Login]$ python2
Python 2.7.18 (default, Mar 15 2021, 14:29:03)
[GCC 10.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pwn import *
>>> r = process("/tmp/test")
[x] Starting local process '/tmp/test'
[+] Starting local process '/tmp/test': pid 14870
>>> r.read()
'Welcome to my ultra secure login service!\n'
>>> r.read()
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hacker/.local/lib/python2.7/site-packages/pwnlib/tubes/tube.py", line 1405, in wrapper
    return func(self, *a, **kw)
  File "/home/hacker/.local/lib/python2.7/site-packages/pwnlib/tubes/tube.py", line 82, in recv
    return self._recv(numb, timeout) or b''
  File "/home/hacker/.local/lib/python2.7/site-packages/pwnlib/tubes/tube.py", line 160, in _recv
    if not self.buffer and not self._fillbuffer(timeout):
  File "/home/hacker/.local/lib/python2.7/site-packages/pwnlib/tubes/tube.py", line 131, in _fillbuffer
    data = self.recv_raw(self.buffer.get_fill_size())
  File "/home/hacker/.local/lib/python2.7/site-packages/pwnlib/tubes/process.py", line 701, in recv_raw
    if not self.can_recv_raw(self.timeout):
  File "/home/hacker/.local/lib/python2.7/site-packages/pwnlib/tubes/process.py", line 745, in can_recv_raw
    return select.select([self.proc.stdout], [], [], timeout) == ([self.proc.stdout], [], [])
KeyboardInterrupt
>>> r.send("\n")
>>> r.read()
[*] Process '/tmp/test' stopped with exit code 0 (pid 14870)
'Generated Password is }\x02\xddG{\xc2\xa0\xc3v\x81\xa8\xaa\xb1M\x01\x16I\x91~\x8c\xb9x\xc8o6fX\xfaWF\x18z2|Q9\x7f\xb30\xc0"`\xa8\x85\xf0\xfa8\x82z\xb8/\x11\xdf\xbd\x98\x1bi\x8a\xba\x84\x84\x90\x01\xdcO/\xd6.\xd4:\x13\x93Enter the password: Wrong!\n'
>>> r.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hacker/.local/lib/python2.7/site-packages/pwnlib/tubes/process.py", line 643, in __getattr__
    raise AttributeError("'process' object has no attribute '%s'" % attr)
AttributeError: 'process' object has no attribute 'start'
>>> r
<pwnlib.tubes.process.process object at 0x7f6240818410>
>>> r = process("/tmp/test")
[x] Starting local process '/tmp/test'
[+] Starting local process '/tmp/test': pid 14888
>>> r.read()
'Welcome to my ultra secure login service!\nGenerated Password is \xd3\xb1\x91d[\xbd"%\x80\x89O\xea\n'
>>> r.read()
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hacker/.local/lib/python2.7/site-packages/pwnlib/tubes/tube.py", line 1405, in wrapper
    return func(self, *a, **kw)
  File "/home/hacker/.local/lib/python2.7/site-packages/pwnlib/tubes/tube.py", line 82, in recv
    return self._recv(numb, timeout) or b''
  File "/home/hacker/.local/lib/python2.7/site-packages/pwnlib/tubes/tube.py", line 160, in _recv
    if not self.buffer and not self._fillbuffer(timeout):
  File "/home/hacker/.local/lib/python2.7/site-packages/pwnlib/tubes/tube.py", line 131, in _fillbuffer
    data = self.recv_raw(self.buffer.get_fill_size())
  File "/home/hacker/.local/lib/python2.7/site-packages/pwnlib/tubes/process.py", line 701, in recv_raw
    if not self.can_recv_raw(self.timeout):
  File "/home/hacker/.local/lib/python2.7/site-packages/pwnlib/tubes/process.py", line 745, in can_recv_raw
    return select.select([self.proc.stdout], [], [], timeout) == ([self.proc.stdout], [], [])
KeyboardInterrupt
>>> r.send("\xd3\xb1\x91d[\xbd"%\x80\x89O\xea\n")
  File "<stdin>", line 1
    r.send("\xd3\xb1\x91d[\xbd"%\x80\x89O\xea\n")
                                                ^
SyntaxError: unexpected character after line continuation character
>>> r.send("\xd3\xb1\x91d[\xbd"%\x80\x89O\xea")
  File "<stdin>", line 1
    r.send("\xd3\xb1\x91d[\xbd"%\x80\x89O\xea")
                                              ^
SyntaxError: unexpected character after line continuation character
>>> r.send("\xd3\xb1\x91d[\xbd"%\x80\x89O\xea\n")
  File "<stdin>", line 1
    r.send("\xd3\xb1\x91d[\xbd"%\x80\x89O\xea\n")
                                                ^
SyntaxError: unexpected character after line continuation character
>>> r.send("\xd3\xb1\x91d[\xbd\"%\x80\x89O\xea\n")
>>> r.read()
[*] Process '/tmp/test' stopped with exit code 1 (pid 14888)
'Enter the password: Error: missing flag.txt.\n'
